version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
  httpd:
    build:
      context: .
      dockerfile: Dockerfile-httpd
    image: my-httpd:test
    ports:
      - "80:80"
volumes:
  jenkins_home:

